# Your personal number for sending SMS messages FROM
# Must be a Twilio-verified number
TWILIO_PHONE_NUMBER = "+160xxxxxxxx"
TWILIO_ACCOUNT_SID = "AC3ed76xxxxxxxxxxxxxxxxxxxxx"
TWILIO_AUTH_TOKEN = "1973ea2bfxxxxxxxxxxxxxxxxxxxxxx"

# Your email credentials for sending emails
# IMPORTANT: For Gmail, you MUST generate an "App Password". Your regular password will not work.
# Search "Google App Password" to learn how.
SENDER_EMAIL = "your.email@gmail.com"
SENDER_PASSWORD = "your-generated-google-app-password"

# AWS Credentials
# Create an IAM user with programmatic access in your AWS account
AWS_ACCESS_KEY_ID = "AKIAXXXXXXXXXXXXXXXX"
AWS_SECRET_ACCESS_KEY = "YourSuperSecretAwsAccessKey"
AWS_DEFAULT_REGION = "us-east-1"  # Or your preferred region

# Google Gemini API Key
# Get this from Google AI Studio
GEMINI_API_KEY = "AIzaSyCNeFxRzQ7ONVZ-3AaXF46okSllbsIXgnM"
